apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stratus
resources:
  - namespace.yaml
  - configmap.yaml
  - rbac.yaml
  - api-deployment.yaml
  - workers.yaml
  - hpa.yaml
  - networkpolicy.yaml
commonLabels:
  app.kubernetes.io/part-of: stratus
